//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class costos_receta_materias_primas
    {
        public int id { get; set; }
        public int id_receta { get; set; }
        public int id_materia_prima { get; set; }
        public int cantidad { get; set; }
        public string unidad_de_medida { get; set; }
        public decimal costo_por_cantidad { get; set; }
        public Nullable<decimal> total_costo { get; set; }
    
        public virtual tabla_materias_primas tabla_materias_primas { get; set; }
        public virtual tabla_costos_recetas tabla_costos_recetas { get; set; }
    }
}
