//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class costos_receta_materias_primas_utilizadas
    {
        public int id { get; set; }
        public Nullable<int> id_receta { get; set; }
        public Nullable<int> id_materia_prima_utilizada { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string unidad_de_medida { get; set; }
        public Nullable<decimal> costo_por_cantidad { get; set; }
        public Nullable<decimal> total_costo { get; set; }
    
        public virtual tabla_costos_recetas tabla_costos_recetas { get; set; }
        public virtual tabla_materias_primas tabla_materias_primas { get; set; }
    }
}
