//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_CREANDO_RECUERDOSEntities : DbContext
    {
        public BD_CREANDO_RECUERDOSEntities()
            : base("name=BD_CREANDO_RECUERDOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tabla_categorias> tabla_categorias { get; set; }
        public virtual DbSet<tabla_clientes> tabla_clientes { get; set; }
        public virtual DbSet<tabla_detalle_venta> tabla_detalle_venta { get; set; }
        public virtual DbSet<tabla_empaque_decoracion> tabla_empaque_decoracion { get; set; }
        public virtual DbSet<tabla_ingredientes_recetas> tabla_ingredientes_recetas { get; set; }
        public virtual DbSet<tabla_materias_primas> tabla_materias_primas { get; set; }
        public virtual DbSet<tabla_procedimientos_recetas> tabla_procedimientos_recetas { get; set; }
        public virtual DbSet<tabla_productos> tabla_productos { get; set; }
        public virtual DbSet<tabla_productos_preparados> tabla_productos_preparados { get; set; }
        public virtual DbSet<tabla_proveedores> tabla_proveedores { get; set; }
        public virtual DbSet<tabla_recetas> tabla_recetas { get; set; }
        public virtual DbSet<tabla_roles> tabla_roles { get; set; }
        public virtual DbSet<tabla_suministros> tabla_suministros { get; set; }
        public virtual DbSet<tabla_usuarios> tabla_usuarios { get; set; }
        public virtual DbSet<tabla_ventas> tabla_ventas { get; set; }
    }
}
