//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_ventas
    {
        public tabla_ventas()
        {
            this.tabla_detalle_venta = new HashSet<tabla_detalle_venta>();
        }
    
        public int id_venta { get; set; }
        public int id_usuario { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public decimal total { get; set; }
    
        public virtual tabla_clientes tabla_clientes { get; set; }
        public virtual ICollection<tabla_detalle_venta> tabla_detalle_venta { get; set; }
        public virtual tabla_usuarios tabla_usuarios { get; set; }
    }
}
