//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_recetas
    {
        public tabla_recetas()
        {
            this.tabla_ingredientes_recetas = new HashSet<tabla_ingredientes_recetas>();
            this.tabla_procedimientos_recetas = new HashSet<tabla_procedimientos_recetas>();
        }
    
        public int id_receta { get; set; }
        public string nombre { get; set; }
        public decimal cantidad { get; set; }
        public string unidad_medida { get; set; }
        public decimal costo_por_unidad { get; set; }
        public decimal costo_total { get; set; }
        public decimal costo_total_receta { get; set; }
        public decimal costo_por_porcion { get; set; }
    
        public virtual ICollection<tabla_ingredientes_recetas> tabla_ingredientes_recetas { get; set; }
        public virtual ICollection<tabla_procedimientos_recetas> tabla_procedimientos_recetas { get; set; }
    }
}
