//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_ingredientes_recetas
    {
        public int id_ingrediente { get; set; }
        public int id_receta { get; set; }
        public int id_materia_prima { get; set; }
        public int id_producto_preparado { get; set; }
        public decimal cantidad { get; set; }
        public string presentacion { get; set; }
    
        public virtual tabla_materias_primas tabla_materias_primas { get; set; }
        public virtual tabla_productos_preparados tabla_productos_preparados { get; set; }
        public virtual tabla_recetas tabla_recetas { get; set; }
    }
}
