//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_empaque_decoracion
    {
        public int id_empaque { get; set; }
        public int id_materia_prima { get; set; }
        public string nombre { get; set; }
        public string presentacion { get; set; }
        public int unidad_cantidad { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> costo_por_unidad { get; set; }
    
        public virtual tabla_materias_primas tabla_materias_primas { get; set; }
    }
}
