//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_notificaciones_vistas
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_vista { get; set; }
    
        public virtual tabla_ventas tabla_ventas { get; set; }
        public virtual tabla_usuarios tabla_usuarios { get; set; }
    }
}
