//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_proveedores
    {
        public tabla_proveedores()
        {
            this.tabla_materias_primas = new HashSet<tabla_materias_primas>();
            this.tabla_productos_preparados = new HashSet<tabla_productos_preparados>();
        }
    
        public int id_proveedor { get; set; }
        public string nombre { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<tabla_materias_primas> tabla_materias_primas { get; set; }
        public virtual ICollection<tabla_productos_preparados> tabla_productos_preparados { get; set; }
    }
}
