//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_actividades
    {
        public int id_actividad { get; set; }
        public int id_usuario { get; set; }
        public string tipo_accion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string tabla_afectada { get; set; }
        public Nullable<int> id_registro_afectado { get; set; }
        public string valores_anteriores { get; set; }
        public string valores_nuevos { get; set; }
    
        public virtual tabla_usuarios tabla_usuarios { get; set; }
        public virtual tabla_usuarios tabla_usuarios1 { get; set; }
    }
}
