//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_procedimientos_recetas
    {
        public int id_procedimiento { get; set; }
        public int id_receta { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual tabla_recetas tabla_recetas { get; set; }
    }
}
