//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_horarios
    {
        public int id_horario { get; set; }
        public int id_usuario { get; set; }
        public string dia_semana { get; set; }
        public System.TimeSpan hora_entrada { get; set; }
        public System.TimeSpan hora_salida { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual tabla_usuarios tabla_usuarios { get; set; }
    }
}
