//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_costos_recetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_costos_recetas()
        {
            this.costos_receta_materias_primas = new HashSet<costos_receta_materias_primas>();
            this.costos_receta_productos_preparados = new HashSet<costos_receta_productos_preparados>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public decimal costo_total_receta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costos_receta_materias_primas> costos_receta_materias_primas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costos_receta_productos_preparados> costos_receta_productos_preparados { get; set; }
        public virtual tabla_precios_finales_sugeridos tabla_precios_finales_sugeridos { get; set; }
    }
}
