//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_recomendaciones
    {
        public int id_recomendacion { get; set; }
        public int id_producto { get; set; }
        public string motivo { get; set; }
    
        public virtual tabla_productos tabla_productos { get; set; }
    }
}
