//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_valoraciones
    {
        public int id_valoracion { get; set; }
        public int id_pedido { get; set; }
        public int calificacion { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual tabla_ventas tabla_ventas { get; set; }
    }
}
