//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_notificaciones_vistas
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_vista { get; set; }
    
        public virtual tabla_ventas tabla_ventas { get; set; }
        public virtual tabla_usuarios tabla_usuarios { get; set; }
    }
}
