//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_materias_primas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_materias_primas()
        {
            this.tabla_empaque_decoracion = new HashSet<tabla_empaque_decoracion>();
            this.tabla_ingredientes_recetas = new HashSet<tabla_ingredientes_recetas>();
            this.tabla_productos_preparados = new HashSet<tabla_productos_preparados>();
            this.tabla_suministros = new HashSet<tabla_suministros>();
        }
    
        public int id_materia_prima { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> costo_por_gramo { get; set; }
        public Nullable<decimal> costo_por_porcion { get; set; }
        public Nullable<decimal> porcentaje_merma { get; set; }
        public Nullable<decimal> costo_por_merma { get; set; }
        public Nullable<decimal> costo_por_gramo_con_merma { get; set; }
        public Nullable<decimal> costo_por_porcion_con_merma { get; set; }
        public Nullable<decimal> costo_total_mas_merma { get; set; }
        public int id_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_empaque_decoracion> tabla_empaque_decoracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_ingredientes_recetas> tabla_ingredientes_recetas { get; set; }
        public virtual tabla_proveedores tabla_proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_productos_preparados> tabla_productos_preparados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_suministros> tabla_suministros { get; set; }
    }
}
