//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_productos
    {
        public tabla_productos()
        {
            this.tabla_detalle_venta = new HashSet<tabla_detalle_venta>();
        }
    
        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int id_categoria { get; set; }
        public decimal precio_por_unidad { get; set; }
    
        public virtual tabla_categorias tabla_categorias { get; set; }
        public virtual ICollection<tabla_detalle_venta> tabla_detalle_venta { get; set; }
    }
}
