//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_suministros
    {
        public int id_suministro { get; set; }
        public int id_materia_prima { get; set; }
        public string nombre { get; set; }
        public string presentacion { get; set; }
        public int unidad_cantidad { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> costo_por_unidad { get; set; }
    
        public virtual tabla_materias_primas tabla_materias_primas { get; set; }
    }
}
