//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_costos_recetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_costos_recetas()
        {
            this.costos_receta_materias_primas_utilizadas = new HashSet<costos_receta_materias_primas_utilizadas>();
            this.costos_receta_productos_preparados_utilizados = new HashSet<costos_receta_productos_preparados_utilizados>();
            this.tabla_precios_finales_sugeridos = new HashSet<tabla_precios_finales_sugeridos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public decimal costo_total_receta { get; set; }
        public int porcion { get; set; }
        public decimal costo_por_porcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costos_receta_materias_primas_utilizadas> costos_receta_materias_primas_utilizadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costos_receta_productos_preparados_utilizados> costos_receta_productos_preparados_utilizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_precios_finales_sugeridos> tabla_precios_finales_sugeridos { get; set; }
    }
}
