//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_precios_finales_sugeridos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_precios_finales_sugeridos()
        {
            this.precios_empaques_decorativos = new HashSet<precios_empaques_decorativos>();
            this.precios_implementos_utilizados = new HashSet<precios_implementos_utilizados>();
            this.precios_suministro_utilizados = new HashSet<precios_suministro_utilizados>();
        }
    
        public int id { get; set; }
        public string nombre_receta { get; set; }
        public decimal costo_total_receta { get; set; }
        public decimal utilidad { get; set; }
        public Nullable<decimal> costo_sin_utilidad { get; set; }
        public Nullable<decimal> costo_con_margen_de_utilidad { get; set; }
        public Nullable<decimal> costo_empaque_decoracion { get; set; }
        public Nullable<decimal> costo_implemento { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> impuesto_de_servicio { get; set; }
        public string plataforma_envio { get; set; }
        public Nullable<decimal> envio { get; set; }
        public Nullable<decimal> precio_final_sugerido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<precios_empaques_decorativos> precios_empaques_decorativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<precios_implementos_utilizados> precios_implementos_utilizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<precios_suministro_utilizados> precios_suministro_utilizados { get; set; }
        public virtual tabla_costos_recetas tabla_costos_recetas { get; set; }
    }
}
