//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_precios_finales_sugeridos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_precios_finales_sugeridos()
        {
            this.precios_empaques_decoraciones_utilizados = new HashSet<precios_empaques_decoraciones_utilizados>();
            this.precios_implementos_utilizados = new HashSet<precios_implementos_utilizados>();
            this.precios_suministros_utilizados = new HashSet<precios_suministros_utilizados>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_receta { get; set; }
        public string nombre_receta { get; set; }
        public Nullable<decimal> costo_total_receta { get; set; }
        public decimal margen_de_utilidad { get; set; }
        public Nullable<decimal> costo_sin_margen_de_utilidad { get; set; }
        public Nullable<decimal> costo_con_margen_de_utilidad { get; set; }
        public Nullable<decimal> costo_empaque_decoracion_utilizado { get; set; }
        public Nullable<decimal> costo_implemento_utilizado { get; set; }
        public Nullable<decimal> costo_suministro_utilizado { get; set; }
        public Nullable<decimal> costo_con_iva { get; set; }
        public Nullable<decimal> costo_con_servicio { get; set; }
        public Nullable<decimal> envio { get; set; }
        public string plataforma_de_envio { get; set; }
        public Nullable<decimal> precio_final_sugerido { get; set; }
        public Nullable<decimal> costo_de_impresion_de_factura_por_insumo { get; set; }
        public Nullable<decimal> costo_total_de_impresion_de_factura { get; set; }
        public Nullable<decimal> factura_total { get; set; }
        public Nullable<decimal> costo_total_empaque_decoracion_implemento_suministro_por_porcentaje_de_ganancia { get; set; }
        public Nullable<decimal> factura_por_insumo { get; set; }
        public Nullable<decimal> costo_total_insumos { get; set; }
        public Nullable<decimal> porcentaje_de_iva { get; set; }
        public Nullable<decimal> porcentaje_de_servicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<precios_empaques_decoraciones_utilizados> precios_empaques_decoraciones_utilizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<precios_implementos_utilizados> precios_implementos_utilizados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<precios_suministros_utilizados> precios_suministros_utilizados { get; set; }
        public virtual tabla_costos_recetas tabla_costos_recetas { get; set; }
    }
}
