//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_materias_primas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_materias_primas()
        {
            this.costos_receta_materias_primas = new HashSet<costos_receta_materias_primas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string presentacion { get; set; }
        public string proveedor { get; set; }
        public decimal costo { get; set; }
        public int peso { get; set; }
        public string unidad_de_medida { get; set; }
        public Nullable<decimal> costo_por_gramo { get; set; }
        public int merma_total_en_gramos { get; set; }
        public Nullable<decimal> porcentaje_de_merma { get; set; }
        public Nullable<decimal> costo_de_merma_total { get; set; }
        public Nullable<decimal> costo_total_mas_merma_total { get; set; }
        public Nullable<decimal> costo_por_gramo_con_merma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costos_receta_materias_primas> costos_receta_materias_primas { get; set; }
    }
}
