//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_categorias
    {
        public tabla_categorias()
        {
            this.tabla_productos = new HashSet<tabla_productos>();
        }
    
        public int id_categoria { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<tabla_productos> tabla_productos { get; set; }
    }
}
