//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_recomendaciones
    {
        public int id_recomendacion { get; set; }
        public int id_producto { get; set; }
        public string motivo { get; set; }
    
        public virtual tabla_productos tabla_productos { get; set; }
    }
}
