//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_proveedores
    {
        public tabla_proveedores()
        {
            this.tabla_materias_primas = new HashSet<tabla_materias_primas>();
            this.tabla_productos_preparados = new HashSet<tabla_productos_preparados>();
        }
    
        public int id_proveedor { get; set; }
        public string nombre { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<tabla_materias_primas> tabla_materias_primas { get; set; }
        public virtual ICollection<tabla_productos_preparados> tabla_productos_preparados { get; set; }
    }
}
