//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_productos_preparados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_productos_preparados()
        {
            this.costos_receta_productos_preparados = new HashSet<costos_receta_productos_preparados>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string presentacion { get; set; }
        public string proveedor { get; set; }
        public int porcion { get; set; }
        public decimal costo { get; set; }
        public int peso { get; set; }
        public string unidad_de_medida { get; set; }
        public Nullable<decimal> costo_por_peso { get; set; }
        public Nullable<decimal> costo_por_porcion_con_merma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costos_receta_productos_preparados> costos_receta_productos_preparados { get; set; }
    }
}
