//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_ingredientes_recetas
    {
        public int id_ingrediente { get; set; }
        public int id_receta { get; set; }
        public int id_materia_prima { get; set; }
        public int id_producto_preparado { get; set; }
        public decimal cantidad { get; set; }
        public string presentacion { get; set; }
    
        public virtual tabla_materias_primas tabla_materias_primas { get; set; }
        public virtual tabla_productos_preparados tabla_productos_preparados { get; set; }
        public virtual tabla_recetas tabla_recetas { get; set; }
    }
}
