//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_usuarios()
        {
            this.tabla_actividades = new HashSet<tabla_actividades>();
            this.tabla_horarios = new HashSet<tabla_horarios>();
            this.tabla_solicitudes_ausencias = new HashSet<tabla_solicitudes_ausencias>();
            this.tabla_ventas = new HashSet<tabla_ventas>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public int id_rol { get; set; }
        public string correo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string contrasenna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_actividades> tabla_actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_horarios> tabla_horarios { get; set; }
        public virtual tabla_roles tabla_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_solicitudes_ausencias> tabla_solicitudes_ausencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_ventas> tabla_ventas { get; set; }
    }
}
