//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_ventas()
        {
            this.tabla_detalle_venta = new HashSet<tabla_detalle_venta>();
            this.tabla_notificaciones_vistas = new HashSet<tabla_notificaciones_vistas>();
            this.tabla_valoraciones = new HashSet<tabla_valoraciones>();
        }
    
        public int id_venta { get; set; }
        public int id_usuario { get; set; }
        public int id_cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public decimal total { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> tiempo_estimado { get; set; }
        public string metodo_pago { get; set; }
        public Nullable<bool> para_llevar { get; set; }
        public string pin { get; set; }
        public string notificacion { get; set; }
        public string numero_pedido { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string telefono { get; set; }
        public string telefono_sinpe { get; set; }
    
        public virtual tabla_clientes tabla_clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_detalle_venta> tabla_detalle_venta { get; set; }
        public virtual tabla_estados_pedido tabla_estados_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_notificaciones_vistas> tabla_notificaciones_vistas { get; set; }
        public virtual tabla_usuarios tabla_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_valoraciones> tabla_valoraciones { get; set; }
    }
}
