//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_productos_preparados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabla_productos_preparados()
        {
            this.tabla_ingredientes_recetas = new HashSet<tabla_ingredientes_recetas>();
        }
    
        public int id_producto_preparado { get; set; }
        public int id_materia_prima { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string presentacion { get; set; }
        public int id_proveedor { get; set; }
        public decimal costo { get; set; }
        public decimal cantidad { get; set; }
        public string unidad_medida { get; set; }
        public decimal costo_por_unidad { get; set; }
        public decimal costo_total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabla_ingredientes_recetas> tabla_ingredientes_recetas { get; set; }
        public virtual tabla_materias_primas tabla_materias_primas { get; set; }
        public virtual tabla_proveedores tabla_proveedores { get; set; }
    }
}
