//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_materias_primas
    {
        public tabla_materias_primas()
        {
            this.tabla_empaque_decoracion = new HashSet<tabla_empaque_decoracion>();
            this.tabla_ingredientes_recetas = new HashSet<tabla_ingredientes_recetas>();
            this.tabla_productos_preparados = new HashSet<tabla_productos_preparados>();
            this.tabla_suministros = new HashSet<tabla_suministros>();
        }
    
        public int id_materia_prima { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<decimal> costo_por_gramo { get; set; }
        public Nullable<decimal> costo_por_porcion { get; set; }
        public Nullable<decimal> porcentaje_merma { get; set; }
        public Nullable<decimal> costo_por_merma { get; set; }
        public Nullable<decimal> costo_por_gramo_con_merma { get; set; }
        public Nullable<decimal> costo_por_porcion_con_merma { get; set; }
        public Nullable<decimal> costo_total_mas_merma { get; set; }
        public int id_proveedor { get; set; }
    
        public virtual ICollection<tabla_empaque_decoracion> tabla_empaque_decoracion { get; set; }
        public virtual ICollection<tabla_ingredientes_recetas> tabla_ingredientes_recetas { get; set; }
        public virtual tabla_proveedores tabla_proveedores { get; set; }
        public virtual ICollection<tabla_productos_preparados> tabla_productos_preparados { get; set; }
        public virtual ICollection<tabla_suministros> tabla_suministros { get; set; }
    }
}
