//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_CreandoRecuerdos.base_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_procedimientos_recetas
    {
        public int id_procedimiento { get; set; }
        public int id_receta { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual tabla_recetas tabla_recetas { get; set; }
    }
}
